-- 添加 PENDING_SOLD 状态到 customers 表的 status 字段
ALTER TABLE customers 
MODIFY COLUMN status ENUM('NEW', 'CONTACTED', 'SCHEDULED', 'PENDING_CONFIRM', 'VISITED', 'RE_EXPERIENCE', 'PENDING_SOLD', 'SOLD', 'CLOSED') 
NOT NULL DEFAULT 'NEW' 
COMMENT '客户状态';

